# Generated by Django 5.1.5 on 2026-01-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='face_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
